[package]
name = "ratadata"
version = "0.1.0"
authors = ["Pedro Jordão <pedrohjordao@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rats = { git = "https://github.com/rust-rats/rats" }
